### ISSUE TITLE
 Is it possible to make this fake gpu in Vulkan? 

### ISSUE THREAD

**Issue by VelasquezZZ12** [FakeMichau/fakenvapi#5]
Is it possible to make this fake gpu in Vulkan? I managed to get the optiscaler to work but unfortunately the dlss option doesn't appear in the game

**Comment by FakeMichau** [comment]
What is the game? 
NMS only work on non-AMD, Baldur's Gate 3 works, Path of Exile 2 works, Indiana Jones only works on Nvidia, Doom Ethernal requires goghor's winmm.dll to make the game load DLSS.

**Comment by VelasquezZZ12** [comment]
in the Indian game with amd.
Is it possible to use an option that tricks the system about vram usage?
in rtx
